// Pure reducer for the learner's draft → review → save loop. A review is only
// valid for the exact {draft_revision, knowledge_revision_id} it assessed;
// anything else is stale and ignored. The backend (WS6) enforces the same rule
// server-side — this keeps the UI honest and prevents accidental double submits.
import { outcomeToReviewState } from "@/lib/practice/outcomeToReviewState";
import type { LearnerEvaluation, ReviewStatus } from "@/lib/ui/contracts";

export type ReviewMachineState = {
  status: ReviewStatus;
  draft_revision: number;
  knowledge_revision_id: string;
  /** Draft revision whose review is pending or was received; null when none. */
  requested_revision: number | null;
  evaluation: LearnerEvaluation | null;
  /** Key of the current save intent (generated by the caller to keep this pure). */
  idempotency_key: string | null;
  error: string | null;
};

export type ReviewEvent =
  | { type: "EDIT" }
  | { type: "REQUEST_REVIEW" }
  | { type: "EVALUATION_RECEIVED"; evaluation: LearnerEvaluation }
  | { type: "REVIEW_FAILED"; error: string }
  | { type: "KNOWLEDGE_REVISION_CHANGED"; knowledge_revision_id: string }
  /** An expert entry was removed from teaching (WS6 `entry.revoked`). */
  | { type: "KNOWLEDGE_REVOKED"; entry_id: string }
  | { type: "SAVE_REQUESTED"; idempotency_key: string }
  | { type: "SAVE_ACKED" }
  | { type: "SAVE_FAILED"; error: string }
  | { type: "RESET" };

export function initialReviewState(knowledgeRevisionId: string): ReviewMachineState {
  return {
    status: "editing_unreviewed",
    draft_revision: 1,
    knowledge_revision_id: knowledgeRevisionId,
    requested_revision: null,
    evaluation: null,
    idempotency_key: null,
    error: null,
  };
}

/** Back to "not yet reviewed": nothing reviewed carries over. */
function unreviewed(state: ReviewMachineState, patch: Partial<ReviewMachineState>): ReviewMachineState {
  return {
    ...state,
    status: "editing_unreviewed",
    requested_revision: null,
    evaluation: null,
    idempotency_key: null,
    error: null,
    ...patch,
  };
}

export function reviewMachine(state: ReviewMachineState, event: ReviewEvent): ReviewMachineState {
  const { status } = state;
  switch (event.type) {
    case "EDIT":
      // Inputs are locked while a save is in flight; a saved draft is final.
      if (status === "saving" || status === "saved") return state;
      return unreviewed(state, { draft_revision: state.draft_revision + 1 });

    case "REQUEST_REVIEW":
      // After guidance the learner must change the draft before asking again.
      if (status !== "editing_unreviewed") return state;
      return { ...state, status: "review_pending", requested_revision: state.draft_revision, error: null };

    case "EVALUATION_RECEIVED": {
      const ev = event.evaluation;
      const current =
        status === "review_pending" &&
        ev.draft_revision === state.draft_revision &&
        ev.draft_revision === state.requested_revision &&
        ev.knowledge_revision_id === state.knowledge_revision_id;
      if (!current) return state;
      return { ...state, status: outcomeToReviewState(ev.outcome), evaluation: ev };
    }

    case "REVIEW_FAILED":
      if (status !== "review_pending") return state;
      return unreviewed(state, { error: event.error });

    case "KNOWLEDGE_REVISION_CHANGED":
      if (status === "saved" || event.knowledge_revision_id === state.knowledge_revision_id) return state;
      return unreviewed(state, { knowledge_revision_id: event.knowledge_revision_id });

    case "KNOWLEDGE_REVOKED": {
      // WS6 marks evaluations that relied on a revoked entry stale; a pending one may rely on it too.
      const cited = state.evaluation?.citations.some(c => c.entry_id === event.entry_id) ?? false;
      if (status === "saved" || (status !== "review_pending" && !cited)) return state;
      return unreviewed(state, {});
    }

    case "SAVE_REQUESTED":
      // save_failed keeps the still-current evaluation, so Retry is a save of the same reviewed revision.
      if (status !== "review_complete" && status !== "save_failed") return state;
      if (state.evaluation === null) return state;
      return { ...state, status: "saving", idempotency_key: event.idempotency_key, error: null };

    case "SAVE_ACKED":
      if (status !== "saving") return state;
      return { ...state, status: "saved" };

    case "SAVE_FAILED":
      if (status !== "saving") return state;
      return { ...state, status: "save_failed", error: event.error };

    case "RESET":
      if (status === "saving") return state;
      return initialReviewState(state.knowledge_revision_id);
  }
}
